# PyTorch Tutorial #2
제목: 파이토치(PyTorch)로 딥러닝하기: 60분만에 끝장내기  
링크: https://tutorials.pytorch.kr/beginner/blitz/autograd_tutorial.html

### Autograd

In [2]:
# initialization
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)   # requires_grad=True를 설정하여 연산을 기록
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)   # y는 연산의 결과임으로 grad_fn을 갖음

In [7]:
z = y * y * 3
out = z.mean()

print(z , out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [12]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
print(a.grad_fn)         # requires_grad가 False기 때문에 None
a.requires_grad_(True)   # requires_grad를 in-place로 변경    
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


### Gradient
* torch.autograd는 벡터-야코비안 곱을 계산하는 엔진

In [13]:
out.backward()
print(x.grad)   # d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [14]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  217.3224, -1093.0464,  1057.3492], grad_fn=<MulBackward0>)


In [15]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [16]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():               # .no_grad()로 코드 블럭을 감싸 추적을 멈출 수 있음
    print((x ** 2).requires_grad)

True
True
False


In [18]:
print(x.requires_grad)
y = x.detach()           # .detach()는 동일한 content에 requires_grad가 다른 새로운 tensor를 생성함
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
